/*
 * @Author: gaoyang334 gaoyang334@jd.com
 * @Date: 2025-06-18 10:44:39
 * @LastEditors: gaoyang334 gaoyang334@jd.com
 * @LastEditTime: 2025-07-01 18:00:21
 * @FilePath: /dark/src/app/layout.tsx
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
import type { Metadata } from "next";
import "@/app/globals.css";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.container}>
      {/* 头部 */}
      {<div className={styles.header}>Dark in light</div>}

      {/* 内容区域 */}
      <div className={styles.content}>{children}</div>

      {/* 脚部 */}
      {<div className={styles.footer}>Valar Morghulis</div>}
    </div>
  );
}
